# This is a basic workflow to help you get started with Actions

name: Test-SSApp-build-process

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Triggers the workflow at the end of the day
  schedule:
    - cron: "0 0 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: github-actions-tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Node version
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install psmisc for killall
      - name: Install psmisc package
        run: sudo apt-get install -y psmisc

      # install dependencies
      - name: Install dependencies (dev-install)
        run: npm run dev-install

      # install dependencies
      - name: Install dependencies (install-mobile)
        run: npm run install-mobile

      # create a replacement for missing sleep cmd
      - name: sleep-alternative
        run: echo 'console.log("TIC"); setTimeout(()=>{console.log("TAC")}, process.argv[3])' >> timeout.js
        
      # prepare test script
      - name: Prepare test script
        run: echo 'npm run server &' >> run-test.sh && echo 'node timeout.js 60*1000' >> run-test.sh && echo 'npm run build-all' >> run-test.sh && echo 'npm run build-mobile' >> run-test.sh && echo 'killall -9 node' >> run-test.sh && chmod 711 run-test.sh 
        
      # Run build tests
      - name: Run build tests
        run: ./run-test.sh
